name        = "whitakers_words"
version     = "0.20240801.0"
description = "William Whitaker's WORDS, a Latin dictionary"
licenses    = "Custom-Public-Domain"
authors     = ["William A. Whitaker", "Martin Keegan"]
website     = "http://mk270.github.io/whitakers-words/"
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

project-files = ["commands.gpr"]
# The call to make does everything, this is the one that generates the
# executables. So this is causing an unneeded rebuild, but short of forking and
# adding a dummy project file, this is the best we can do, until Alire allows
# to entirely skip building a project file.

executables   = ["words"]

[configuration]
disabled = true

[[depends-on]]
make = "any"
gnat = "/=7.3" # Bug with SAL library failing binding with GNAT FSF 7.3

[[actions]]
type = "post-fetch"
command = ["make"]
